### ISSUE TITLE
Back button on login page is not functioning

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-language-translation-suite#11]
I entered Language and Resources and was at Login page, wanted to go back to change the Resources option but the Back button would not let me go a step back neither does clicking on Resources on the header.

**Comment by klappy** [comment]
Login is the first step and you can click on the headers to change which step you are in.

Maybe we can find a more obvious visualization for the user to know that.

**Comment by elsylambert** [comment]
Closing this issue. This was submitted when Login wasn't the first step in the stepper. Works fine now.
