### ISSUE TITLE
Heading Sections toggle button is not functioning properly

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-language-translation-suite#13]
Resources page>Select tA>select file Checking>Acceptable , turn on/off the Heading sections toggle button from the Menu. The button does not turn off/on, but the page shows the results. click on the file name again and then the button changes.
Here is the screen recording:
[Video_2019-10-29_101243.zip](https://github.com/unfoldingWord-box3/gateway-language-translation-suite-prototype/files/3783958/Video_2019-10-29_101243.zip)

**Comment by klappy** [comment]
This bug appears to be due to the upgrade from @material-ui v3 to v4. Looked into it but haven't discovered the resolution.

**Comment by klappy** [comment]
Fixed with moving app state's context to the component.

Should be resolved with `0.9.0-alpha.10`

**Comment by elsylambert** [comment]
Working fine in GLtS v0.9.0-alpha.14. Heading Section toggle button puts the text chunks under collapsible headings.
