### ISSUE TITLE
Right hand side content is not loading in tA

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-language-translation-suite#14]
Select tA from the Resources>File>Checking>acceptable. Left hand side content loads up , not the right hand side.
![image](https://user-images.githubusercontent.com/51806180/67778297-594fe980-fa39-11e9-853c-61bf5d1befb3.png)

Click on the 
![image](https://user-images.githubusercontent.com/51806180/67778393-80a6b680-fa39-11e9-82e6-0bc094e24e69.png) link, it takes you to the door43 catalog and the file there is has the Content that should be loaded in the right hand side.

If you are not seeing this issue, follow the below steps:
1. if the page loads up correctly, displaying the content on both the sides, Go to Menu click on the files License.md or readme.md.
2. Open up the Checking> Acceptable file. Note that the right side content is either blank or displaying a invalid content.

**Comment by klappy** [comment]
This issue should be resolved now in v0.9.0-alpha.x

**Comment by elsylambert** [comment]
Working fine in v0.9.0-alpha.5

**Comment by elsylambert** [comment]
Working fine in  v0.9.0-alpha.14
