### ISSUE TITLE
Right hand side content for editing not getting refreshed after the file is changed from the Menu 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-language-translation-suite#17]
Right hand side content for editing not getting refreshed after the file is changed from the Menu 
![image](https://user-images.githubusercontent.com/51806180/68219845-ad684a00-ffb4-11e9-97f6-c6f7a0d96fcf.png)
- Opened Bibles>Names>Haggai file and edited and saved
- Go to Menu>Select another file>(Bible>other>12TribesofIsrael)
-Left hand side loads up as 12TribesofIsrael, but right hand side stays the same as Haggai.

The link to Door 43 from the right hand side(user) goes to 12tribesofisrael.md but the content it shows is of Haggai.md
![image](https://user-images.githubusercontent.com/51806180/68224161-18694f00-ffbc-11e9-9788-8658571b7c27.png)

**Comment by elsylambert** [comment]
This happens in tW, tN and OBS as well.

**Comment by klappy** [comment]
Should be resolved along with: https://github.com/unfoldingWord/gateway-language-translation-suite/issues/19

**Comment by elsylambert** [comment]
Working fine in  v0.9.0-alpha.14
