### ISSUE TITLE
tsv file gets corrupted at d43 when the incorrect file content is displayed in tN

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-language-translation-suite#19]
Related to #17 
Steps to replicate the issue:
1. Open 1 peter.tsv , edit , save.
2. Select hab.tsv(Habakkuk), NOte that the page still shows 1 Peter content, but the file name in header is hab.tsv.
3. Click on the link icon to see the content on D43. Note that hab. tsv displays content from 1 peter.
![image](https://user-images.githubusercontent.com/51806180/68608917-0edf5b80-0482-11ea-816c-3347308ebc57.png)

4. You may logout and login back or may just open the resources page and open Hab. tsv file. Note that the content is 1 peter and actual content of Habakkuk is lost.

**Comment by klappy** [comment]
This should be addressed all tsv editing in v09.0-alpha.x releases. There still remains an issue with `.md` files, sadly it wasn't the same resolution as `.tsv` files.

**Comment by klappy** [comment]
This should now be addressed with .md files as well.

**Comment by RoyalSix** [comment]
Working for me now

**Comment by elsylambert** [comment]
Verified in GLtS v0.9.0-alpha.14. Working fine.
