### ISSUE TITLE
Back button on the browser closes the app

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-language-translation-suite#20]
Back button on the chrome browser closes the app
![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/2cae9b0b-8922-4d22-8d73-2896fdf035ec)

**Comment by klappy** [comment]
I think we might be able to disable the back button.

@jag3773 @birchamp What do you think about addressing this during a feature like what is in the Consume App? Every navigation action yields unique query params that are copy/pasteable to navigate directly to what you are currently viewing. For example `https://glts.door43.org/?rc://unfoldingword/en/tw/tit&language=fr` which would take you to translate en_tw into fr_tw as you're own logged in user and write to your repo.

**Comment by jag3773** [comment]
I would very much like to see permalinks in the app!

**Comment by klappy** [comment]
Should be addressed in build `alpha.25`

**Comment by elsylambert** [comment]
Not an issue in alpha-25. Back button is disabled.
