### ISSUE TITLE
Deployment Process for Develop and Master

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/gateway-language-translation-suite#26]
We should have at least 2 stages of deployment, one matching the `develop` branch and one matching the `master` branch, following git flow.

Ideally, we could have feature branch deployments as well.  This needs to happen automatically so that devs and qa can test at discrete URL endpoints.

**Comment by jag3773** [comment]
As long as this is in the queue, we ought to define the release process for the app as well.

Will we be using semantic versioning?  Date based versioning?  Will we use tags/releases in Github?  Will we support release branches?

**Comment by klappy** [comment]
- Github: `develop` branch created and made default on `gateway-language-translation-suite` repo.
- Netlify branch deploys enabled for `develop` branch: https://develop--glts.netlify.com


- PRs will automatically be created against `develop` branch from here.
- PRs will build and deploy on Netlify for previews.
- Merges to `develop` branch will build and deploy here: https://develop--glts.netlify.com
- QA and others can verify `develop` before merging to `master`.
- When `master` is updated, production will be deployed: https://glts.netlify.com
