### ISSUE TITLE
Book of Judges not showing up in tN resources

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-language-translation-suite#32]
Go to Resources>tN> en_tn_07-JDG.tsv file is not opening. All the other OT books are fine.

**Comment by klappy** [comment]
Once the PR is merged for Gitea React Toolkit, we can increment the version in this app and should address this issue: https://github.com/unfoldingWord/gitea-react-toolkit/pull/20

**Comment by klappy** [comment]
Addressed in build `alpha.21`

**Comment by elsylambert** [comment]
Looks good in alpha -21 in Test Branch.
