### ISSUE TITLE
App crashes when scroll down from Intro section

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-language-translation-suite#33]
- Open a tN resources(.tsv file) 
- Scroll down from the introduction section 
- as soon as it reaches the next Block the App crashes.
[Blank screen.zip](https://github.com/unfoldingWord/gateway-language-translation-suite/files/4013124/Blank.screen.zip)

This is happening for OT books only. NT books are loading fine.
Seems like when the Parallel scripture section comes up the App crashes

**Comment by elsylambert** [comment]
Test comment

**Comment by elsylambert** [comment]
Tested in the Test Build at https://develop--glts.netlify.com./.

The App does not crash while loading Parallel Scriptures ion OT books anymore, But when we switch the book from Menu, the Intro changes to the new book but the Scripture part does not get refreshed to the new one but shows the previous book instead.

**Comment by klappy** [comment]
@elsylambert Do you mind if we either close this issue and create a new one with the new behavior? They aren't directly related. We can rename this issue if you'd like.

**Comment by elsylambert** [comment]
App no longer crashes on scrolling down to Parallel scripture viewer.
