### ISSUE TITLE
Next page button crashes the App after three-four pages.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-language-translation-suite#35]
![image](https://user-images.githubusercontent.com/51806180/71630310-42ac4700-2bd0-11ea-8ea5-2d77cafcd246.png)

Click on the Next button as highlighted in the snapshot about three-four clicks to go to the next pages, App crashes after few clicks.

**Comment by klappy** [comment]
Bug appears to be due to an attempt to fetch a verse that doesn't exist.
`TypeError: Cannot read property '1' of undefined`
Scripture Resources RCL -`src/components/parallel-scripture/helpers.js` in `versesFromReferenceIdAndBooks`:
`var verse = book.chapters[_reference.chapter][_reference.verse];`

**Comment by klappy** [comment]
Addressed with `v0.9.0-alpha.20`

**Comment by RoyalSix** [comment]
Is the fix on the master branch?

**Comment by elsylambert** [comment]
Looks good in v0.9.0-alpha.20. Tested with a large OT and a NT book, pages are loading fine.
