### ISSUE TITLE
Reset Chapter Bug on Blur

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/gateway-language-translation-suite#37]
On blur while editing the Original Quote, jumped back to chapter 1, if the filter is on
(happened during demo)

**Comment by klappy** [comment]
### Good news
The RCL we use for our table has addressed this upstream `MUI-Datatables` version `2.13.x`.
https://github.com/gregnb/mui-datatables/pull/1086

### Bad news
We have already updated to this version and will need to debug further to see what might be causing this.

**Comment by klappy** [comment]
Correction, that does not fix our issue that we are encountering as we provide new data, and it is fixing non-user provided data updates. We will need to persist filtering options ourselves.

**Comment by elsylambert** [comment]
Not seeing this issue in alpha-24.
