### ISSUE TITLE
Milestone rendering issues in Parallel Scripture Viewer

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/gateway-language-translation-suite#40]
Appears to be an issue with rendering milestones.

Here are two examples.

Titus 1:4
![Screen Shot 2020-01-08 at 11.36.52 AM.png](https://images.zenhubusercontent.com/568146ca638e718c995faa57/2ce8fc60-8cec-487f-9373-c36fed5119f8)

Romans 1:4
![Screen Shot 2020-01-08 at 11.35.39 AM.png](https://images.zenhubusercontent.com/568146ca638e718c995faa57/a5fa8e43-436c-4ef4-8593-7c72d806a7e2)

**Comment by klappy** [comment]
Addressed with: https://github.com/unfoldingWord/scripture-resources-rcl/pull/5

**Comment by klappy** [comment]
@elsylambert This should be addressed on develop with `alpha.22`

**Comment by elsylambert** [comment]
Looks good in alpha-23.
