### ISSUE TITLE
Scripture Viewer Hebew RTL support

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/gateway-language-translation-suite#47]

**Comment by klappy** [comment]
Addressed with https://github.com/unfoldingWord/scripture-resources-rcl/pull/4

**Comment by klappy** [comment]
Addressed in build `alpha.21`

**Comment by elsylambert** [comment]
Verified in aplha-21. Hebrew RTL display looks fine. 
@klappy  When Hebrew test is copied in the OriginalText column, it is not displaying spaces. Is that a separate issue from RTL support?

**Comment by jag3773** [comment]
Using `GLtS v0.9.0-alpha.20` I was able to copy Hebrew out of the scripture pane and paste it correctly into the OriginalText column, including spaces.

**Comment by klappy** [comment]
@elsylambert This is a separate issue. When we copy and paste from html, it pastes the html with formatting, sadly the only way to properly paste it at the moment is to use a special keyboard shortcut for pasting without formatting. Mac: `command-shift-v`, Windows: `ctrl-shift-v`.

**Comment by elsylambert** [comment]
Based on klappy's comment, I am passing this issue. Hebrew RTL looks good.
