### ISSUE TITLE
Underline html tags in MD files

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/gateway-language-translation-suite#48]
Most implementations do not support double underscores instead of implementing <u></u>.
Ensure it doesn't add line breaks like it currently is.

**Comment by klappy** [comment]
Fix merged and published as `markdown-translatable@0.10.1`

**Comment by elsylambert** [comment]
Verified in alpha-26.  Double underscores are implemented for Underlines in MD files and are working fine. Not seeing any line breaks.
