### ISSUE TITLE
Only edit/translate file types supported

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/gateway-language-translation-suite#5]
Right now all file types are able to be opened. It would be nice to be able to prevent non-supported file types from being messed up by editing them in the Markdown editor.

Potential solutions:
1. Only open MD files.
2. Open MD files as is, but open the others in a plain text editor without MD parsing.

**Comment by klappy** [comment]
Error message on any file selected other than .md and .tsv: `0.9.0-alpha.14`

**Comment by elsylambert** [comment]
Working fine in GLtS v0.9.0-alpha.14. clicking on a file other than .tsv or .md brings up "File not supported. Please select .tsv or .md file" message.
