### ISSUE TITLE
Scripture Viewer Not updating when Switching books while Editing UTN

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/gateway-language-translation-suite#55]
Tested in the Test Build at https://develop--glts.netlify.com./. on alpha-21

The App does not crash while loading Parallel Scriptures on OT books anymore, But when we switch the book from Menu, the Intro changes to the new book but the Scripture part does not get refreshed to the new one but shows the previous book instead.
![image](https://user-images.githubusercontent.com/51806180/72172481-3a5bc500-33a3-11ea-84e9-22aa87ce4c47.png)

This behaviour is seen in NT book too. Change of Books displays scripture of the previous book selected.

Moved from issue #33 second comment.

**Comment by klappy** [comment]
Addressed with PR #54, build `alpha.23`.

**Comment by elsylambert** [comment]
Tested in alpha-23. Not seeing this issue. Scripture viewer is updated when books are switched.
