### ISSUE TITLE
Edits Lost Using Menu Options

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/gateway-language-translation-suite#7]
When changing font sizes, new props are sent to the edit/translate component which re-renders them. The edits since the last save are lost.

**Comment by klappy** [comment]
Issue Addressed on changing font sizes.

**Comment by klappy** [comment]
- Potentially remove Sectionable from menu and implement it into Markdown-Translatable since it is a concern of that library.
- Possible new component that wraps Document and Section and has a flag to switch the rendering mode and persists changes accordingly.

**Comment by klappy** [comment]
Implemented the mentioned options.

Does not address switching files, closing repository, or logging out. These all still lose edits if not saved.

**Comment by elsylambert** [comment]
Tested in alpha 23. Edits are not lost when Font size is changed.
