### ISSUE TITLE
Optimize use of space for TSV

### ISSUE THREAD

**Issue by ancientTexts-net** [unfoldingWord/gateway-language-translation-suite#997]
From Larry's feedback meeting:
- Scripture pane is displayed for each note on the same verse. Is there a way to group them?  (NOTE: would require a change to OrigQuote highlighting behavior)

tC Create should display TSVs more like gatewayEdit (pictured below) to make better use of the space by reducing whitespace
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/c3675621-fabf-4f3b-b2c5-ac77f603f10c)

DoD:
---
TSVs (specifically TNs) take up less vertical space than before, but function identically.

**Comment by ancientTexts-net** [comment]
https://translation-helps-rcl.netlify.app/#tsvcontent

This component might be helpful to compare to # 997
TSVContent component: maybe better use of whitespace
Are they using css box model? how do they organize the UI ?


@Joel-C-Johnson @jincypjose 
@mandolyte 
@birchamp

**Comment by ancientTexts-net** [comment]
@Joel-C-Johnson @jincypjose 
we might want to ask Birch if he has the figma drawings.  or at least screenshot of the one that relates to this issue please

**Comment by ancientTexts-net** [comment]
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/0847bd4c-fae6-453b-bf1f-3134493004ee)

**Comment by mandolyte** [comment]
I think data table uses a table object, not a layout manager. It has some sort of customization feature that allows us to wrap a row. @klappy I'm sure could say more. Could we start by minimizing the margins and padding?

**Comment by ancientTexts-net** [comment]
compare to TsvContent from gateway edit
(except we don't use styled-components)

https://github.com/unfoldingWord/translation-helps-rcl/blob/main/src/components/TsvContent/TsvContent.js

**Comment by birchamp** [comment]
@mandolyte find the location of code for this.

**Comment by elsylambert** [comment]
translationCore Create - v1.4.0-rc.4 build 108-06d4807
The layout looks like the screenshot shown below: It uses less white space than before.
![Screen Shot 2021-12-22 at 9.49.08 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/f21f04d3-23c7-4f32-8ef3-58a891d37785)

**Comment by ancientTexts-net** [comment]
FYI @elsylambert @jincypjose @Joel-C-Johnson 

When Elsy was testing, she asked about how the ORIG QUOTE field wraps for Hebrew (RIGHT-to-LEFT order)

Following the lines shows how the words wrap, RIGHT-to-LEFT.  "LGTM"  :)))

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/df278ef1-6ebf-43e5-8b9d-cabdecd84ee2)
